// Create minimal valid PNG files
const fs = require('fs');
const path = require('path');

// Minimal 16x16 blue PNG (base64 encoded)
const icon16 = Buffer.from(
  'iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAYAAAAf8/9hAAAAKklEQVR42mNk+M/wn4EIwDhq' +
  'wKgBgzYDGBn+MzISAYwaAAGjBowaMGQNAAD+/wEzPZ3JNQAAAABJRU5ErkJggg==',
  'base64'
);

// Minimal 48x48 blue PNG
const icon48 = Buffer.from(
  'iVBORw0KGgoAAAANSUhEUgAAADAAAAAwCAYAAABXAvmHAAAApElEQVR42u3XMQ0AAAgDMLDJ' +
  'OB52BFdpExAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAP' +
  'wNDgAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAwN/gAAAA' +
  'AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA/wNLhgAEkPBJEAAAAABJRU5ErkJggg==',
  'base64'
);

// Minimal 128x128 blue PNG
const icon128 = Buffer.from(
  'iVBORw0KGgoAAAANSUhEUgAAAIAAAACACAYAAADDPmHLAAAA/ElEQVR42u3QMQ0AAAgDMLDJ' +
  'dBzFIFzpJEgAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA' +
  'AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA' +
  'AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA' +
  'AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA' +
  'AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAD+' +
  'DlcGAAHVNbhdAAAAAElFTkSuQmCC',
  'base64'
);

const dir = __dirname;
fs.writeFileSync(path.join(dir, 'icon16.png'), icon16);
fs.writeFileSync(path.join(dir, 'icon48.png'), icon48);
fs.writeFileSync(path.join(dir, 'icon128.png'), icon128);

console.log('Created icon16.png, icon48.png, icon128.png');
